name: (中文) 功能漏洞或插件不相容
description: 回報關於插件不相容，功能缺失或漏洞相關的問題 
body:
  - type: markdown
    attributes:
      value: |
        在你回報問題之前，請確定你目前運行的是最新版的 ImanityKnockback

  - type: textarea
    attributes:
      label: 預期狀況
      description: 你期望應該要看到什麼?
    validations:
      required: true
  - type: textarea
    attributes:
      label: 實際狀況
      description: 你實際上看到了什麼?
    validations:
      required: true
  - type: textarea
    attributes:
      label: 重現的方式
      description: 可以是一張示意圖、影片或是詳細的說明以幫助重現你回報的問題
    validations:
      required: true
  - type: textarea
    attributes:
      label: 插件列表
      description: 你的伺服器上運行的所有插件
    validations:
      required: true
  - type: textarea
    attributes:
      label: ImanityKnockback 的版本
      description: |
        請在你的伺服器中輸入 `/ver Imanity Knockback` 來獲得你當前的版本。
        請注意 *「最新版」* 並不是一個版本，請提供一個完整的版本號碼！
    validations:
      required: true
  - type: textarea
    attributes:
      label: Spigot 資訊
      description: |
        我們需要知道你在 ImanityKnockback 上運行的是什麼 Spigot。
        還請在伺服器中輸入 `/ver` 提供版本。
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: 同意事項
      description: 請同意以下內容
      options:
        - label: 我正在運行我們 Discord 中 `#imanityKnockback` 頻道提供的最新版本 ImanityKnockback
          required: true
        - label: 我已經搜尋過問題跟踪器並確保沒有發現類似的問題
          required: true

  - type: textarea
    attributes:
      label: 額外資訊
      description: |
        請在下方附上其他有用的資訊。
        我們收到的資訊越多，我們就能更快、更有效地找到問題的解決方案。
    validations:
      required: false

